### ISSUE TITLE
Coordinates missing? Should this be in the config?

### ISSUE THREAD

**Issue by TheBogueRat** [mjtice/MMM-Screendimmer#1]
Not sure how you were pulling the lat/lng for this module, looks like it should be in the config.  At least that's what I had to do for this module to work. Perhaps the readme needs an update?  

> 		{
> 			module: 'MMM-Screendimmer',
> 			config: {
> 				// See below for configurable options
> 				morning: 40,
> 				day: 80,
> 				evening: 40,
> 				night: 20,
> 				query_interval: 30000,
> 				debug: false,
> 				latitude: 33.6598,
> 				longitude: -76.0622
> 			}
> 		},

Thanks for the work on this.  Exactly what I needed for a gift project.

**Comment by mjtice** [comment]
Ah, you're right!  Sorry I forgot that very crucial bit of info.  I've merged your PR, thanks for that.
