### ISSUE TITLE
Instilation

### ISSUE THREAD

**Issue by aareben** [mjtice/MMM-Screendimmer#3]
I'm kinda a noob at this so what do I do after i paste. Is there any way to save that file.

**Comment by mjtice** [comment]
After you paste 
```
{
    module: 'MMM-Screendimmer',
    config: {
        latitude: 34.0000,
        longitude: -75.0000
        // See below for additional configurable options
    }
}
``` 
in your config file?  I'm not sure which editor you're using to write to the config.  But after it's saved then you'll restart the MagicMirror process.  I just do a `killall -9 electron` (not sure if that's appropriate or not but it does the trick).

**Comment by aareben** [comment]
No i know how to do config but what about after I paste this (SUBSYSTEM=="backlight",RUN+="/bin/chmod 666 /sys/class/backlight/%k/brightness /sys/class/backlight/%k/bl_power") in the backlight file. What do I do then?

**Comment by mjtice** [comment]
Save the file, then (in the README.md):

Reload udev rules (or just reboot)
sudo udevadm control --reload-rules

What editor are you using to paste in the command?
